### PR TITLE
fix - loss of context

### PR DESCRIPTION
**Pull request by noobiek**
Fix proposed for #321

### CODE REVIEW

**Comment by akre54** [comment]
Failing tests due to old node. Do the tests pass on your machine?

**Comment by noobiek** [comment]
No, I can't event npm install / yarn.
I get error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
I got node v.9.11.1. Sorry.

**Comment by akre54** [comment]
I just pushed up a few changes to master that should upgrade the packages to their latest version (and fix travis).

Try pulling down master and trying again. If that still doesn't work run `npm install --ignore-engines` or `yarn --ignore-engines`.

Also can you add a test case for this? One that would fail without this patch applied? Thanks!

**Comment by noobiek** [comment]
Yarn gives me --- error An unexpected error occurred: "https://unpm.uberinternal.com/grunt-contrib-jshint/-/grunt-contrib-jshint-1.1.0.tgz: Request failed \"401 Unauthorized\"". ---
So I removed yarn.lock and reinstalled all dependencies.
Tests now run just fine. I'll think of a test for our case.

**Comment by akre54** [comment]
I just removed the yarn.lock file from master. Feel free to go without it.

**Comment by noobiek** [comment]
Ok. This may be a little tricky to explain what happens.
We have 1 prototype of view, 2 descendatns (view1 and view2), 2 models (model1 and model2).

In the onGet() we push current "this.cid" to "var thises=[]" (actually a little more than that, but that was for console.log() convinience to check what happenes).

Push to "thises" happens after
    start = true;
    model1.set({'water':'model1'})
    model2.set({'water':'model2'})

So basically we expect "thises" to have 2 different cid's. 
Without the fix we have there 2 equal cid's of view2. console.log(thises) gives us:
[Object{model: 'model1', view_cid: 'view277'}, Object{model: 'model2', view_cid: 'view277'}]

After the fix we have correct cid's of view1 and view2. consoloe.log(thises) gives us:
[Object{model: 'model1', view_cid: 'view276'}, Object{model: 'model2', view_cid: 'view277'}]

Let me know if anything is not clear.

**Comment by noobiek** [comment]
> also, why not use the existing window.view like the rest of the tests?
If I understand the issue correctly, we need 2 views with same bindings in same proto.
I might be wrong here, but I was not able to reproduce the issue with views of different prototypes.

**Comment by akre54** [comment]
Few minor fixes then lgtm

**Comment by noobiek** [comment]
I am not quite used to github, so I didn't notice your comments were actually for exact lines. So I misunderstood some. Let me know if now I got this right.

**Comment by noobiek** [comment]
I actually can drop "thises" and "start" vars and rewrite onGet() like this:
onGet: function(cid) {
  assert.equals(cid, this.cid);
}

with
model1.set({ cid: view1.cid })
model2.set({ cid: view2.cid })

What do you think?

**Comment by noobiek** [comment]
Maybe this new version is easier to understand?

**Comment by akre54** [comment]
Looks good to me. Thanks for adding the tests :)

**Comment by noobiek** [comment]
My pleasure, @akre54 , thanks for the beautiful lib!

**Pull request merged**
